name: Golang / Security

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "."
