name: Golang / Security

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "."
