name: Golang / Security

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  golang-security-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: ynniss/golang-security-action@master
        with:
          CODE_PATH: "."
